apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PeaversAlwaysSquare
  description: "A World of Warcraft addon that automatically and persistently marks tanks with a square icon."
  annotations:
    github.com/project-slug: peavers-warcraft/PeaversAlwaysSquare
spec:
  type: library
  lifecycle: production
  owner: peavers-warcraft
